sudo: required

language: python

services:
  - docker

script:
  bash bin/run-tests.bash -p $(pwd)/environment/local/postman_environment.json

after_success:
  - export DOCKER_BASE_VERSION=$(cat base-version.txt)
  - export DOCKER_BERKSHIRE_DEV_IMAGE=aldwinb/berkshire-dev:${DOCKER_BASE_VERSION}
  - docker build --rm -t ${DOCKER_BERKSHIRE_DEV_IMAGE} .;
    docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
    docker push ${DOCKER_BERKSHIRE_DEV_IMAGE};
