version: '3'

services:
  app:
    build:
      context: .
    container_name: berkshire-app-1
    volumes:
      - .:/usr/src/app
    depends_on:
      - couchdb
    working_dir: /usr/src/app
    environment:
      - STDIN_OPEN=${STDIN_OPEN}
      - APP_ENV=${APP_ENV:-local}
      - DETACHED=${DETACHED:-0}
    env_file:
      - environment/local/env_vars.bash
    expose:
      - "8081"
    ports:
      - "8081:8081"
    command: ["bash", "bin/app-command.bash"]

  postgresql:
    image: postgres:alpine
    container_name: berkshire-postgres-1
    environment:
      POSTGRES_PASSWORD: berkshire
    volumes:
      - berkshire-postgresql-vol-1:/var/lib/postgresql/data

  couchdb:
    image: klaemo/couchdb:latest
    container_name: berkshire-couchdb-1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: berkshire
    volumes:
      - berkshire-couchdb-vol-1:/opt/couchdb/data

volumes:
  berkshire-postgresql-vol-1:
  berkshire-couchdb-vol-1:
